pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Instalar dependencias') {
             agent{
                docker {
                     image 'python:3.10-slim'
}
}
            steps {
 dir('..') {
                sh 'pip install -r  devops-training-2025-python-app/requirements.txt'
                sh 'pytest -q'}            
}
        }

        stage('Tests') {
            steps {
                sh 'pytest -q'
            }
        }

        stage('Info') {
            steps { 
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}" 
            }
        }
//ejercicio 2
        stage('java Test') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                sh 'mvn test'
            }
        }

    }
}

